### ISSUE TITLE
Does this work with react-router?

### ISSUE THREAD

**Issue by andrictham** [TeamWertarbyte/react-hero-animation#1]

**Comment by leMaik** [comment]
Good question, and yes, it does indeed. :sunglasses: I'm mounting the page that the hero moves to as child of the parent page (since it's a popup in my use-case), using react-router. But is is _supposed_ to work fine in any case with react-router!

That said, there are still some issues and cases where this animation doesn't work at all. I have tried to fix it but didn't have much time to look into it lately. Let me know if you have trouble getting this to work.
